name: Create site list

on:
  push:
    branches: [ master ]
    paths:
      - 'app/src/main/java/com/lagradost/cloudstream3/*providers/*Provider.kt'
      - '.github/workflows/site_list.yml'
      - '.github/site-list.py'
      - 'docs/providers.json'
      - 'app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt'

concurrency: 
  group: "site-list"
  cancel-in-progress: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Edit providers.json
      run: |
        python3 .github/site-list.py
    - name: Commit to the repo
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'chore(docs): update list of sites' || echo
        git push
