name: Fix locale issues

on:
  push:
    branches: [ master ]
    paths:
      - '**.xml'
  workflow_dispatch:

concurrency:
  group: "locale"
  cancel-in-progress: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Generate access token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}

    - uses: actions/checkout@v6
      with:
        token: ${{ steps.app-token.outputs.token }}
        persist-credentials: false

    - name: Install dependencies
      run: pip3 install lxml requests

    - name: Edit files
      run: python3 .github/locales.py

    - name: Commit to the repo
      run: |
        git config --local user.email "111277985+recloudstream[bot]@users.noreply.github.com"
        git config --local user.name "recloudstream[bot]"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'chore(locales): fix locale issues' || echo
        git push
